controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


api_login:
    path: /api/login
    controller: Symfony\Bundle\FrameworkBundle\Controller\AbstractController::json
    methods: [POST]

api_protected_route:
    path: /api/protected
    controller: App\Controller\ApiUserController::userData
    methods: [GET]

# config/routes.yaml
app_react_router:
    path: /{reactRouting}
    controller: App\Controller\AppController::index
    requirements:
        reactRouting: .*